[context.production.environment]
  HUGO_VERSION = "0.78.1"

[build]
publish = "public"
command = "hugo"

[[redirects]]
from = "/dev/*"
force = true
status = 200
conditions = {Role = ["user"]}

[[redirects]]
from = "/userdoc/*"
force = true
status = 200
conditions = {Role = ["user"]}

[[redirects]]
from = "/dev/*"
to = "/"
force = true
status = 302

[[redirects]]
from = "/userdoc/*"
to = "/"
force = true
status = 302

